import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="circle-grid">
          {(() => {
            const items = []; // Array to hold JSX elements
            // Loop logic
            for (let i = 0; i < 104; i++) {
              items.push(<div className="circle-inside-grid" key={i}></div>);
            }
            return items; // Returning the array of JSX elements
          })()}
        </div>
        <div className="shape circle"></div>
        <div className="shape square"></div>
        {children}
      </body>
    </html>
  );
}
